---

package:
  version: 35.0.0
  whiteboard:
    version: 2.0.0
  appsToRestore:
  - 'bookmarks'
  - 'spreed'
  - 'deck'
  - 'mail'
  - 'notes'
  - 'contacts'
  - 'tasks'
  - 'drawio'
  - 'whiteboard'
  - 'richdocuments'
  - 'forms'
  - 'calendar'
  appsToInstall:
  - 'bookmarks'
  - 'spreed'
  - 'deck'
  - 'mail'
  - 'notes'
  - 'contacts'
  - 'tasks'
  - 'drawio'
  - 'forms'
  - 'calendar'
