---

- name: install check pre requisites
  apt: 
    name:
    - mutt
    state: present

- name: Mail personnal folder
  file:
    path: '/root/mail'
    state: 'directory'
    owner: root
    group: root
    mode: '0755'

- name: Mail global spool folder
  file:
    path: '/var/spool/mail/'
    state: 'directory'
    owner: root
    group: root
    mode: '0644'

- name: Configuraiton mutt
  template:
    src: muttrc
    dest: /root/.muttrc
    owner: root
    group: root
    mode: '0644'

- name: Check version script
  template:
    src: checkVersion.sh
    dest: /opt/checkVersion.sh
    owner: root
    group: root
    mode: '0744'

- name: Check version service
  copy:
    src: checkVersion.service
    dest: /etc/systemd/system/checkVersion.service
    owner: root
    group: root
    mode: '0644'

- name: Check version timer
  copy:
    src: checkVersion.timer
    dest: /etc/systemd/system/checkVersion.timer
    owner: root
    group: root
    mode: '0644'

- name: Check version enabling
  systemd:
    name: 'checkVersion.timer'
    enabled: yes
