---

- name: Restore database Redmine
  include_role:
    name : pg_restore_database
  vars:
  - pg_filename: 'redmine-last.dmp'
  - pg_username: '{{ dbschema.redmine.username }}'
  - pg_database: '{{ dbschema.redmine.database }}'

- name: Restore files from pcloud Redmine
  include_role:
    name : pcloud_restore_file
  vars:
  - foldername: '/data/redmine-files'
  - filename: 'redmine-last-files.tar'

- name: Uncompress data Redmine
  unarchive:
    src: '/data/redmine-files/redmine-last-files.tar'
    dest: '/'
    remote_src: 'yes'
    owner: nobody
    group: nogroup

- name: generate redmine token
  shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-{{ruby.version}}/bin; bin/rake generate_secret_token
  args:
    chdir: '/opt/redmine/'
  become_user: redmine

- name: migrate redmine database
  shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-{{ruby.version}}/bin; RAILS_ENV=production bin/rake db:migrate
  args:
    chdir: '/opt/redmine/'
  become_user: redmine

- name: Remove old archive Redmine Redmine
  file:
    path: '/data/redmine-files/redmine-last-files.tar'
    state: 'absent'
