---

- name: Update DNS
  include_role:
    name : update_infomaniak_dns
  vars:
    targetExtension : '{{keycloak.domain.suffix}}'
    targetIP: '{{ansible_default_ipv4.address}}'
  when: not redmine_unsecured

- name: Ensure group "keycloak" exists
  group:
    name: keycloak
    state: present

- name: Add the user 'keycloak'
  user:
    name: keycloak
    group: keycloak

- name: Create dedicated database
  include_role:
    name : pg_new_fresh_database
  vars:
    pg_username: '{{ dbschema.keycloak.username }}'
    pg_password: '{{ dbschema.keycloak.password }}'
    pg_database: '{{ dbschema.keycloak.database }}'
  when: not already_installed.stat.exists is defined or not already_installed.stat.exists

- name: nginx service reload/start
  systemd:
    name: 'nginx'
    daemon_reload: true
    state: started
    enabled: true

- name: generate keycloak certificate
  shell: /usr/bin/certbot certonly -d {{ keycloak.domain.suffix }}.{{ server.domain.sub}}{{server.domain.main }} -m {{ server.domain.contact }} --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html  --keep-until-expiring --non-interactive
  when: not redmine_unsecured
      
# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  template:
    src: keycloak.conf
    dest: /opt/nginx/conf/server/keycloak.conf

- name: Nginx service restart with full configuration
  systemd:
    name: 'nginx'
    state: restarted


# https://green.cloud/docs/how-to-install-java-jdk-21-or-openjdk-21-on-debian-12/
