---
- name: main playbook
  hosts: all

  become: true

  roles:
    - socle_config
    - postgresql
    - redmine
#    - nginx
    - nextcloud
    - gogs
    - gitea
    - etherpad
    - ethercalc
    - spliit
    - fail2ban
    - backup
    - monit
    - check_version
    - logo
    - autoconfig_mail
    - uptime_kuma
    - restore_data
    - rustdesk
    - netdata
    - netdata_conf
#    - keycloak
