---
- name: monit installation
  apt: 
    name:
    - monit
    state: present

- name: settings.cfg
  copy:
    src:  config/settings.cfg
    dest: /etc/monit/conf.d/settings.cfg
    owner: root
    group: root
    mode: '0600'

- name: system.cfg
  template:
    src:  system.cfg
    dest: /etc/monit/conf.d/system.cfg
    owner: root
    group: root
    mode: '0600'

- name: Monit service restart with full configuration
  systemd:
    name: 'monit'
    state: restarted

- name: generate monit certificate
  shell: /usr/bin/certbot certonly -d {{ monit.domain.suffix }}.{{ server.domain.dns }} -m {{ server.domain.contact }} --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html  --keep-until-expiring --non-interactive  
  when: not redmine_unsecured
      
# finish installation with ssl termination
- name: Template nginx configuration file
  template:
    src: monit.conf
    dest: /opt/nginx/conf/server/monit.conf

- name: Nginx service restart with full configuration
  systemd:
    name: 'nginx'
    state: restarted

