---
# [system]
# system_configuration for php 7.0:
php_ver: "7.0"
php_dir: "/etc/php/7.0"
php_bin: "php-fpm7.0"
php_pkg_apcu: "php-apcu"
php_pkg_spe:
  - "php-imap"
  - "php-imagick"
  - "php-redis"
  - "php7.0-mcrypt"
  - "php7.0-xml"
  - "php7.0-zip"
  - "php7.0-mbstring"
php_socket: "/run/php/php7.0-fpm.sock"
