---
# put the autoconfiguration email client file in public access


- name: Update DNS
  include_role:
    name : update_infomaniak_dns
  vars:
    targetExtension : '{{autoconfig.domain.suffix}}'
    targetIP: '{{ansible_default_ipv4.address}}'
  when: not redmine_unsecured

- name: directory for files under /data
  file:
    path: /data/autoconfig-files/mail
    state: 'directory'
    owner: 'nobody'
    group: 'nogroup'

- name: configuration mail servers
  template:
    src: config.xml
    dest: /data/autoconfig-files/mail/config-v1.1.xml

- name: generate static certificate
  shell: /usr/bin/certbot certonly -d {{ autoconfig.domain.suffix }}.{{ server.domain.sub}}{{server.domain.main }} -m {{ server.domain.contact }} --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html  --keep-until-expiring --non-interactive
  when: not redmine_unsecured

# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  template:
    src: autoconfig.conf
    dest: /opt/nginx/conf/server/autoconfig.conf

- name: Nginx service restart with full configuration
  systemd:
    name: 'nginx'
    state: restarted
