---

- name: generate redmine certificate
  shell: /usr/bin/certbot certonly -d gogs.meallier.fr -m eric@meallier.fr --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html  --keep-until-expiring --non-interactive  

- name: Gogs service reload/start
  systemd:
    name: 'gogs'
    daemon_reload: true
    state: started
    enabled: true
  
# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  copy:
    src: gogsSSL.conf
    dest: /opt/nginx/conf/server/gogsSSL.conf

- name: Nginx service restart with full configuration
  systemd:
    name: 'nginx'
    state: restarted
