---

- name: Restore applications
  include_tasks:
    file : '{{app_name}}'
  loop:
    - restore_redmine.yml
    - restore_gogs.yml
    - restore_nextcloud.yml
  loop_control:
    loop_var: app_name
