---

- name: Restore database Redmine
  include_role:
    name : pg_restore_database
  vars:
  - pg_filename: 'redmine-last.dmp'
  - pg_username: '{{ postgresql.redmine.username }}'
  - pg_database: '{{ postgresql.redmine.database }}'

- name: Restore files from pcloud Redmine
  include_role:
    name : pcloud_restore_file
  vars:
  - foldername: '/data/redmine-files'
  - filename: 'redmine-last-files.tar'

- name: Uncompress data Redmine
  unarchive:
    src: '/data/redmine-files/redmine-last-files.tar'
    dest: '/'
    remote_src: 'yes'
    owner: nobody
    group: nogroup

- name: Remove old archive Redmine Redmine
  file:
    path: '/data/redmine-files/redmine-last-files.tar'
    state: 'absent'


- name: Restore database Gogs
  include_role:
    name : pg_restore_database
  vars:
  - pg_filename: 'gogs-last.dmp'
  - pg_username: '{{ postgresql.gogs.username }}'
  - pg_database: '{{ postgresql.gogs.database }}'

- name: Restore files from pcloud Gogs
  include_role:
    name : pcloud_restore_file
  vars:
  - foldername: '/data/gogs-repositories'
  - filename: 'gogs-last-data.tar'

- name: Uncompress data Gogs
  unarchive:
    src: '/data/gogs-repositories/gogs-last-data.tar'
    dest: '/'
    remote_src: 'yes'
    owner: gogs
    group: gogs

- name: Remove old archive Gogs
  file:
    path: '/data/gogs-repositories/gogs-last-data.tar'
    state: 'absent'



- name: Restore database Nextcloud
  include_role:
    name : pg_restore_database
  vars:
  - pg_filename: 'nextcloud-last.dmp'
  - pg_username: '{{ postgresql.nextcloud.username }}'
  - pg_database: '{{ postgresql.nextcloud.database }}'

- name: Mise à jour de l'environnement occ
  shell: 
    cmd: 'sudo -u nobody php{{ php.version }} occ upgrade'
    chdir: '/opt/nextcloud'

- name: Disable TOTP for users
  shell: 
    cmd: 'sudo -u nobody php{{ php.version }} occ twofactorauth:disable {{ item }}'
    chdir: '/opt/nextcloud'
  loop:
  - 'administrator'
  - 'rickou_412'
    
- name: Restore files from pcloud Nextcloud
  include_role:
    name : pcloud_restore_file
  vars:
  - foldername: '/data/nextcloud'
  - filename: 'nextcloud-last-data.tar'

- name: Uncompress data Nextcloud
  unarchive:
    src: '/data/nextcloud/nextcloud-last-data.tar'
    dest: '/'
    remote_src: 'yes'
    owner: nobody
    group: nogroup

- name: Remove old archive Nextcloud
  file:
    path: '/data/nextcloud/nextcloud-last-data.tar'
    state: 'absent'