---

- name: Stop applications
  systemd:
    name: '{{ service_name }}'
    state: stopped
  loop:
  - 'monit'
  - 'nginx.service'
  - 'php{{ php.version }}-fpm'
  loop_control:
    loop_var: service_name
  ignore_errors: True

- name: Restore database Nextcloud
  include_role:
    name : pg_restore_database
  vars:
    pg_filename: 'nextcloud-last.dmp'
    pg_username: '{{ dbschema.nextcloud.username }}'
    pg_database: '{{ dbschema.nextcloud.database }}'

- name: Mise à jour de l'environnement occ
  shell: 
    cmd: 'sudo -u nobody php{{ php.version }} occ upgrade'
    chdir: '/opt/nextcloud'

- name: Disable TOTP for users
  shell: 
    cmd: 'sudo -u nobody php{{ php.version }} occ twofactorauth:disable {{ item }} totp'
    chdir: '/opt/nextcloud'
  loop:
  - 'administrator'
  - 'rickou_412'
    
- name: Restore files from pcloud Nextcloud
  include_role:
    name : pcloud_restore_file
  vars:
    foldername: '/data/nextcloud'
    filename: 'nextcloud-last-data.tar'

- name: Uncompress data Nextcloud
  unarchive:
    src: '/data/nextcloud/nextcloud-last-data.tar'
    dest: '/'
    remote_src: 'yes'
    owner: nobody
    group: nogroup

- name: Remove old archive Nextcloud
  file:
    path: '/data/nextcloud/nextcloud-last-data.tar'
    state: 'absent'

- name: Restart applications
  systemd:
    name: '{{ service_name }}'
    state: started
  loop:
  - 'php{{ php.version }}-fpm'
  - 'nginx.service'
  - 'monit'
  loop_control:
    loop_var: service_name

