---

- name: Update DNS
  ansible.builtin.include_role:
    name: update_infomaniak_dns
  vars:
    update_infomaniak_dns_target_extension: '{{ redmine.domain.suffix }}'
    update_infomaniak_dns_target_ip: '{{ ansible_default_ipv4.address }}'
  when: not redmine_unsecured

- name: Install redmine pre requisites
  ansible.builtin.apt:
    name:
    - libmagickwand-dev
    - postgresql-client-{{ postgresql.version }}
    - postgresql-server-dev-{{ postgresql.version }}
    - imagemagick
    - git
    state: present

- name: Is already installed ?
  ansible.builtin.stat:
    path: "/opt/redmine/config/database.yml"
  register: already_installed

- name: Is already downloaded ?
  ansible.builtin.stat:
    path: '/tmp/redmine-{{ package.version }}.{{ package.type }}'
  register: already_zip

- name: Create dedicated database
  ansible.builtin.include_role:
    name: pg_new_fresh_database
  vars:
    pg_new_fresh_database_pg_username: '{{ dbschema.redmine.username }}'
    pg_new_fresh_database_pg_password: '{{ dbschema.redmine.password }}'
    pg_new_fresh_database_pg_database: '{{ dbschema.redmine.database }}'
  when: not already_installed.stat.exists is defined or not already_installed.stat.exists

- name: Install pg client
  ansible.builtin.shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-{{ ruby.version }}/bin; gem install pg -v '{{ package.gems.pg }}'

- name: Ensure group "redmine" exists
  ansible.builtin.group:
    name: redmine
    state: present

- name: Add the user 'redmine'
  ansible.builtin.user:
    name: redmine
    group: redmine

- name: Adding user redmine to rvm users
  ansible.builtin.user:
    name: 'redmine'
    groups:
      - 'rvm'
    append: yes

- name: Backup old installation, if needed
  ansible.builtin.copy:
    remote_src: true
    src: '/opt/redmine/config/{{ item }}'
    dest: '/opt/{{ item }}'
  ignore_errors: true
  register: ignore_errors_register
  loop:
    - 'configuration.yml'
    - 'database.yml'
  when: already_installed.stat.exists is defined and already_installed.stat.exists

- name: Cleanup target folder
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
  - '/opt/redmine-{{ package.version }}'
  - '/opt/redmine'

- name: Download redmine files
  ansible.builtin.get_url:
    url: https://www.redmine.org/releases/redmine-{{ package.version }}.{{ package.type }}
    dest: /tmp/redmine-{{ package.version }}.{{ package.type }}
    checksum: sha256:{{ package.checksum.sha256 }}
  when: not already_zip.stat.exists is defined or not already_zip.stat.exists

- name: Extract redmine files into /opt
  ansible.builtin.unarchive:
    src: /tmp/redmine-{{ package.version }}.{{ package.type }}
    dest: /opt
    remote_src: 'yes'
    owner: 'nobody'
    group: 'rvm'
    mode: '775'

- name: Link to current version
  ansible.builtin.file:
    src: /opt/redmine-{{ package.version }}
    dest: /opt/redmine
    state: 'link'
    owner: 'nobody'
    group: 'rvm'

- name: Copy database configuration file
  ansible.builtin.template:
    src: database.yml
    dest: /opt/redmine/config/database.yml
    owner: 'nobody'
    group: 'rvm'
    mode: '0644'
  when: not already_installed.stat.exists is defined or not already_installed.stat.exists

- name: Copy mail configuration file
  ansible.builtin.template:
    src: configuration.yml
    dest: /opt/redmine/config/configuration.yml
    owner: 'nobody'
    group: 'rvm'
    mode: '0644'
  when: not already_installed.stat.exists is defined or not already_installed.stat.exists

- name: Restore old configuration, if needed
  ansible.builtin.command: mv /opt/{{ item }} /opt/redmine/config/{{ item }}
  loop:
    - 'configuration.yml'
    - 'database.yml'
  ignore_errors: true
  register: ignore_errors_register
  when: already_installed.stat.exists is defined and already_installed.stat.exists

- name: Configure bundle tools
  ansible.builtin.shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-{{ ruby.version }}/bin; bundle config set --local without 'development test'
  args:
    chdir: '/opt/redmine/'
  become_user: redmine

- name: Configure redmine user to retrieve gems
  ansible.builtin.shell: chmod -R g+w /usr/local/rvm/rubies/ruby-{{ ruby.version }}/lib/ruby/gems/{{ ruby.reducedversion }}

- name: Retrieve dependencies for redmine
  ansible.builtin.shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-{{ ruby.version }}/bin; bundle install
  args:
    chdir: '/opt/redmine/'
  become_user: redmine

- name: Generate redmine token
  ansible.builtin.shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-{{ ruby.version }}/bin; bin/rake generate_secret_token
  args:
    chdir: '/opt/redmine/'
  become_user: redmine

- name: Migrate redmine database
  ansible.builtin.shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-{{ ruby.version }}/bin; RAILS_ENV=production bin/rake db:migrate
  args:
    chdir: '/opt/redmine/'
  become_user: redmine

- name: Directory for files under /data
  ansible.builtin.file:
    path: /data/redmine-files
    state: 'directory'
    owner: 'nobody'
    group: 'nogroup'

- name: Remove default files directory
  ansible.builtin.file:
    path: /opt/redmine-{{ package.version }}/files
    state: 'absent'

- name: Link to data directory
  ansible.builtin.file:
    src: /data/redmine-files
    dest: /opt/redmine-{{ package.version }}/files
    state: 'link'
    owner: 'nobody'
    group: 'nogroup'

- name: Permission to tmp directory
  ansible.builtin.file:
    path: /opt/redmine-{{ package.version }}/tmp
    state: 'directory'
    mode: '777'
    owner: 'nobody'
    group: 'nogroup'
    recurse: true

- name: Generate redmine certificate
  ansible.builtin.shell: /usr/bin/certbot certonly -d {{ redmine.domain.suffix }}.{{ server.domain.sub }}{{ server.domain.main }} -m {{ server.domain.contact }} --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html --keep-until-expiring --non-interactive
  when: not redmine_unsecured

# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  ansible.builtin.template:
    src: redmine.conf
    dest: /opt/nginx/conf/server/redmine.conf

- name: Nginx service restart with full configuration
  ansible.builtin.systemd:
    name: 'nginx'
    state: restarted

- name: Logrotate configuration
  ansible.builtin.copy:
    src: logrotate
    dest: /etc/logrotate.d/redmine

- name: Cleanup installation
  ansible.builtin.file:
    path: '/tmp/redmine-{{ package.version }}.{{ package.type }}'
    state: 'absent'
