---

- name: install redmine pre requisites
  apt: 
    name:
    - curl
    - gnupg2
    - libcurl4-openssl-dev
    - libmagickwand-dev
    - postgresql-client-11
    - postgresql-server-dev-11
    - unzip
    - imagemagick
    state: present

- name: adding gpg key for rvm
  shell: gpg --keyserver hkp://pgp.mit.edu:80  --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  
- name: check is rvm already installed
  stat:
    path: /usr/local/rvm
  register: rvmExists
  
- name: install rvm
  shell: \curl -sSL https://get.rvm.io | bash -s stable
  when: not rvmExists.stat.isdir is defined or not rvmExists.stat.isdir

- name: Adding user root to rvm users
  user:
    name: 'root'
    group: 'rvm'
    append: yes

- name: install ruby 2.7.5
  shell: /usr/local/rvm/bin/rvm install 2.7.5

- name: use 2.7.5 ruby version
  shell: /usr/local/rvm/bin/rvm --default use 2.7.5

- name: install bundler
  shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-2.7.5/bin; gem install bundler -v '2.3.8'

- name: install pg client
  shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-2.7.5/bin; gem install pg -v '1.3.3'

- name: install rmagick
  shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-2.7.5/bin; gem install rmagick -v '4.2.4'

- name: install passenger
  shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-2.7.5/bin; gem install passenger -v '6.0.12'

- name: check if nginx already exists
  stat: 
    path: /opt/nginx/sbin/nginx
  register: nginx_exists

- name: install nginx with passenger
  shell: passenger-install-nginx-module --auto --auto-download --prefix=/opt/nginx --languages ruby
  environment:
    GEM_PATH: '/usr/local/rvm/gems/ruby-2.7.5:/usr/local/rvm/gems/ruby-2.7.5@global'
    GEM_HOME: '/usr/local/rvm/gems/ruby-2.7.5'
    PATH: '/usr/local/rvm/gems/ruby-2.7.5/bin:/usr/local/rvm/gems/ruby-2.7.5@global/bin:/usr/local/rvm/rubies/ruby-2.7.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/bin'
  when: not nginx_exists.stat.exists

- name: Ensure group "redmine" exists
  group:
    name: redmine
    state: present

- name: Add the user 'redmine'
  user:
    name: redmine
    group: redmine

- name: Adding user redmine to rvm users
  user:
    name: 'redmine'
    group: 'rvm'
    append: yes

- name: Download redmine files
  get_url:
    url: https://www.redmine.org/releases/redmine-4.2.4.tar.gz
    dest: /tmp/redmine-4.2.4.tar.gz
    checksum: sha256:cf649f5d4ff783582f82bebd4a5099ef63acb3d5573bbe6b4bf64f293c61c9ce
    
- name: Extract redmine files into /opt
  unarchive:
    src: /tmp/redmine-4.2.4.tar.gz
    dest: /opt
    remote_src: 'yes'
    owner: redmine
    group: redmine

- name: Copy database configuration file
  template:
    src: database.yml
    dest: /opt/redmine-4.2.4/config/database.yml
    owner: redmine
    group: redmine
    mode: '0644'

- name: retreive dependencies for redmine
  shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-2.7.5/bin; bundle install --path=.
  args:
    chdir: '/opt/redmine-4.2.4/'
  become_user: redmine

- name: generate redmine token
  shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-2.7.5/bin; bin/rake generate_secret_token
  args:
    chdir: '/opt/redmine-4.2.4/'
  become_user: redmine

- name: migrate redmine database
  shell: PATH=$PATH:/usr/local/rvm/rubies/ruby-2.7.5/bin; RAILS_ENV=production bin/rake db:migrate
  args:
    chdir: '/opt/redmine-4.2.4/'
  become_user: redmine

- name: directory for files under /data
  file:
    path: /data/redmine-files
    state: 'directory'
    owner: 'redmine'
    group: 'redmine'

- name: remove default files directory
  file:
    path: /opt/redmine-4.2.4/files
    state: 'absent'

- name: link to data directory
  file:
    src: /data/redmine-files
    dest: /opt/redmine-4.2.4/files
    state: 'link'
    owner: 'redmine'
    group: 'redmine'
  
- name: permission to tmp directory
  file:
    path: /opt/redmine-4.2.4/tmp
    state: 'touch'
    mode: '777'

- name: Install nginx service script
  copy:
    src: nginx.service
    dest: /etc/systemd/system/nginx.service
    owner: root
    group: root
    mode: '0644'

- name: Copy minimal nginx configuration file
  copy:
    src: minimal.conf
    dest: /opt/nginx/conf/nginx.conf

- name: Create external configuration for nginx
  file:
    path: /opt/nginx/conf/server
    state: 'directory'
    mode: '0755'
  
- name: Nginx service reload/start
  systemd:
    name: 'nginx'
    daemon_reload: true
    state: started
    enabled: true

- name: 'Insecure configuration (for Vagrant)'
  include: unsecure.yml
  when: redmine_unsecured
    
- name: 'Secure configuration (for Internet)'
  include: secure.yml
  when: not redmine_unsecured

- name: logrotate configuration
  copy:
    src: logrotate
    dest: /etc/logrotate.d/redmine
