---

# certbot installation
- name: install certobot wth dependencies
  apt: 
    name:
    - certbot
    state: present

- name: create acme challenge folder
  file:
    path: /opt/nginx/html/.well-known/acme-challenge
    state: directory
    recurse: yes
    owner: redmine
    group: redmine
    mode: u+rxw,g+rw,o+rw

- name: generate redmine certificate
  shell: /usr/bin/certbot certonly -d redmine.meallier.fr -m eric@meallier.fr --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html  --keep-until-expiring --non-interactive

- name: check is DH already exists
  stat:
    path: /etc/redmine.dhparam.pem
  register: DHExists

- name: generate Secure Diffie-Hellman
  shell: /usr/bin/openssl dhparam -out /etc/redmine.dhparam.pem 4096
  when: not DHExists.stat.exists is defined or not DHExists.stat.exists

# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  copy:
    src: redmineSSL.conf
    dest: /opt/nginx/conf/server/redmineSSL.conf

- name: Nginx service restart with full configuration
  systemd:
    name: 'nginx'
    state: restarted

- name: Install renew certificate in crontab
  copy: 
    src: crontab
    dest: /etc/cron.d/certbotRenew

- name: Ensure default certbot renew is disabled
  file:
    path: /etc/cron.d/certbot
    state: absent

