---

- name: Copy unsecured nginx configuration file
  copy:
    src: redmineUnsecured.conf
    dest: /opt/nginx/conf/server/redmineUnsecured.conf

- name: Nginx service reload/start
  systemd:
    name: 'nginx'
    daemon_reload: true
    state: restarted
    enabled: true
