---

- name: install backup pre requisites
  apt: 
    name:
    - jq
    state: present

- name: Backup folder creation
  file:
    path: '/backup'
    state: 'directory'
    mode: '0777'

- name: Copy backup script
  template:
    src: backup.sh
    dest: /opt/backup.sh
    owner: root
    group: root
    mode: '0600'

- name: Copy backup service
  copy:
    src: backup.service
    dest: /etc/systemd/system/backup.service
    owner: root
    group: root
    mode: '0644'

- name: Copy backup timer
  copy:
    src: backup.timer
    dest: /etc/systemd/system/backup.timer
    owner: root
    group: root
    mode: '0644'

- name: Backup service enabling
  systemd:
    name: 'backup.timer'
    enabled: yes
