---

- name: Upgrade packages to the latest version
  apt: 
    name: "*"
    state: latest
    update_cache: yes

- name: install socle packages
  apt: 
    name:
    - unzip
    - systemd-timesyncd
    - ufw
    - acl
    state: present

- name: Data folder creation
  file:
    path: '/data'
    state: 'directory'
    mode: '0777'
    owner: root
    group: root

- name: Disable Root Login and Password
  copy:
    src: disable_root_login.conf
    dest: /etc/ssh/sshd_config.d/disable_root_login.conf

- name: Remove ntp daemon if present
  apt:
    name:
    - ntp
    state: absent

- name: Configuration timezone for the server
  shell: 
    cmd: 'timedatectl set-timezone {{ server.timezone}}'

- name: Configure systemd timesync for Europe pool
  copy:
    src: 'timesyncd.conf'
    dest: '/etc/systemd/timesyncd.conf'

- name: Customize message of the day motd
  copy:
    src: 'motd'
    dest: '/etc/motd'

- name: Enable Time synchronization
  command: '/usr/bin/timedatectl set-ntp true'

- name: Restart Time synchronization service
  systemd:
    name: 'systemd-timesyncd'
    daemon_reload: true
    state: 'restarted'
    enabled: true

- name: Configuration firewall
  block:
  - name: Reset firewall
    ufw: 
      state: reset
  - name: Ouverture firewall entrant (ssh, http, https, ssh for gogs)
    ufw:
      rule: 'allow'
      proto: 'tcp'
      port: '{{ item }}'
    loop:
    - '22'
    - '80'
    - '443'

  - name: Ouverture firewall sortant (https, smtps, dns, ntp, http (pour APT), imap(s) + smtp(s) pour portail mail dans nextcloud)
    ufw:
      rule: 'allow'
      direction: 'out'
      port: '{{ item }}'
    loop:
    - '443'
    - '587'
    - '53'
    - '123'
    - '80'
    - '993'

  - name: Ouverture firewall sortant (UDP DHCP)
    ufw:
      rule: 'allow'
      direction: 'out'
      port: '{{ item }}'
    loop:
    - '67'
    
  - name: Deny by default for outgoing
    ufw:
      default: 'deny'
      direction: 'outgoing'

  always:
    - name: UFW enabled
      ufw:
        state: 'enabled'

# certbot installation
- name: install certobot with dependencies
  apt: 
    name:
    - certbot
    state: present

- name: create acme challenge folder
  file:
    path: /opt/nginx/html/.well-known/acme-challenge
    state: directory
    recurse: yes
    owner: nobody
    group: nogroup
    mode: u+rxw,g+rw,o+rw

- name: check is DH already exists
  stat:
    path: /etc/redmine.dhparam.pem
  register: DHExists
  when: not redmine_unsecured

# could take long - around 10 minutes on a vultr VPS
- name: generate Secure Diffie-Hellman
  shell: /usr/bin/openssl dhparam -out /etc/redmine.dhparam.pem 4096
  when: not redmine_unsecured and ( not DHExists.stat.exists is defined or not DHExists.stat.exists)

- name: certbot deploy hook
  copy:
    src: restartNginx.sh
    dest: /etc/letsencrypt/renewal-hooks/deploy/restartNginx.sh
    mode: '0644'
  when: not redmine_unsecured