---

- name: install socle packages
  apt: 
    name:
    - unzip
    - systemd-timesyncd
    - ufw
    state: present
    update_cache: yes

- name: Data folder creation
  file:
    path: '/data'
    state: 'directory'
    mode: '0777'
    owner: root
    group: root

- name: Disable Root Login and Password
  copy:
    src: disable_root_login.conf
    dest: /etc/ssh/sshd_config.d/disable_root_login.conf

- name: Remove ntp daemon if present
  apt:
    name:
    - ntp
    state: absent

- name: Configuration timezone for the server
  shell: 
    cmd: 'timedatectl set-timezone {{ server.timezone}}'

- name: Configure systemd timesync for Europe pool
  copy:
    src: 'timesyncd.conf'
    dest: '/etc/systemd/timesyncd.conf'

- name: Customize message of the day motd
  copy:
    src: 'motd'
    dest: '/etc/motd'

- name: Enable Time synchronization
  command: '/usr/bin/timedatectl set-ntp true'

- name: Restart Time synchronization service
  systemd:
    name: 'systemd-timesyncd'
    daemon_reload: true
    state: 'restarted'
    enabled: true

- name: Configure the kernel to keep connections alive when enabling the firewall
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: 1
    state: present
    sysctl_set: yes
    reload: yes

- name: Configuration firewall
  block:
  - name: Reset firewall
    ufw: 
      state: reset
  - name: Ouverture firewall entrant (ssh, http, https, ssh for gogs)
    ufw:
      rule: 'allow'
      proto: 'tcp'
      port: '{{ item }}'
    loop:
    - '22'
    - '80'
    - '443'

  - name: Ouverture firewall sortant (https, smtps, dns, ntp, http (pour APT), imap(s) + smtp(s) pour portail mail dans nextcloud)
    ufw:
      rule: 'allow'
      direction: 'out'
      port: '{{ item }}'
    loop:
    - '443'
    - '587'
    - '53'
    - '123'
    - '80'
    - '993'

  - name: Ouverture firewall sortant (UDP DHCP)
    ufw:
      rule: 'allow'
      direction: 'out'
      port: '{{ item }}'
    loop:
    - '67'
    
  - name: Deny by default for outgoing
    ufw:
      default: 'deny'
      direction: 'outgoing'

  always:
    - name: UFW enabled
      ufw:
        state: 'enabled'
