---

- name: install socle packages
  apt: 
    name:
    - unzip
    - systemd-timesyncd
    - ufw
    state: present
    update_cache: yes

- name: Data folder creation
  file:
    path: '/data'
    state: 'directory'
    mode: '0777'
    owner: root
    group: root

- name: Disable Root Login and Password
  copy:
    src: disable_root_login.conf
    dest: /etc/ssh/ssh_config.d/disable_root_login.conf

- name: Remove ntp daemon if present
  apt:
    name:
    - ntp
    state: absent

- name: Configure systemd timesync for Europe pool
  copy:
    src: 'timesyncd.conf'
    dest: '/etc/systemd/timesyncd.conf'

- name: Enable Time synchronization
  command: '/usr/bin/timedatectl set-ntp true'

- name: Restart Time synchronization service
  systemd:
    name: 'systemd-timesyncd'
    daemon_reload: true
    state: 'restarted'
    enabled: true

- name: Ouverture firewall entrant (ssh, http, https)
  ufw:
    rule: 'allow'
    proto: 'tcp'
    port: '{{ item }}'
  loop:
  - '22'
  - '80'
  - '443'

- name: Ouverture firewall sortant (https, smtps, dns, ntp, http (pour APT))
  ufw:
    rule: 'allow'
    direction: 'out'
    port: '{{ item }}'
  loop:
  - '443'
  - '465'
  - '53'
  - '123'
  - '80'

- name: Deny by default for outgoing
  ufw:
    default: 'deny'
    direction: 'outgoing'

- name: UFW enabled
  ufw:
    state: 'enabled'
