---

- name: install socle packages
  apt: 
    name:
    - unzip
    state: present
    update_cache: yes

- name: Data folder creation
  file:
    path: '/data'
    state: 'directory'
    mode: '0777'
    owner: root
    group: root

- name: Disable Root Login and Password
  copy:
    src: disable_root_login.conf
    dest: /etc/ssh/ssh_config.d/disable_root_login.conf 
