---
language: python
python: "2.7"
os: linux
dist: xenial
services:
  - mysql
  - redis
matrix:
  include:
    # latest ansible + code coverage
    - env: ansible_version="" NC_DB=mysql NC_WEB=apache2
    - env: ansible_version="" NC_DB=mysql NC_WEB=nginx
    - env: ansible_version="" NC_DB=pgsql NC_WEB=apache2
    - env: ansible_version="" NC_DB=pgsql NC_WEB=nginx
    # backward compatibility:
    # ansible 2.7.x
    - env: ansible_version="<2.8" NC_DB=mysql NC_WEB=apache2
    # ansible 2.6.x
    - env: ansible_version="<2.7" NC_DB=mysql NC_WEB=apache2
    # ansible 2.5.x
    - env: ansible_version="<2.6" NC_DB=mysql NC_WEB=apache2

sudo: required

# Install ansible

before_install:
  - sudo apt-get install python-setuptools
  - sudo easy_install pip
  # Install ansible
  - sudo pip install -I "ansible${ansible_version}"
  - sudo apt-get install python-netaddr


install:
  # Check ansible version
  - ansible --version
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Test Demo case 1
  - ansible-playbook tests/test.yml -i tests/inventory
  # test login pages
  - curl -i -s --insecure --data "user=ncadmin&password=" https://localhost/index.php/login | egrep -q "Location:.*/apps/files/"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
