---

- name: nextcloud service reload/start
  systemd:
    name: 'nginx'
    daemon_reload: true
    state: started
    enabled: true

- name: generate redmine certificate
  shell: /usr/bin/certbot certonly -d nextcloud.meallier.fr -m eric@meallier.fr --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html  --keep-until-expiring --non-interactive  
      
# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  copy:
    src: nextcloudSSL.conf
    dest: /opt/nginx/conf/server/nextcloudSSL.conf

- name: Nginx service restart with full configuration
  systemd:
    name: 'nginx'
    state: restarted
