---

- name: Copy unsecured nginx configuration file
  copy:
    src: nextcloudUnsecured.conf
    dest: /opt/nginx/conf/server/nextcloudUnsecured.conf

- name: Nginx service reload/start
  systemd:
    name: 'nginx'
    daemon_reload: true
    state: started
    enabled: true
