---

- name: generate redmine certificate
  shell: /usr/bin/certbot certonly -d jitsi.meallier.fr -m eric@meallier.fr --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html  --keep-until-expiring --non-interactive  

- name: Jitsi service reload/start
  systemd:
    name: 'jitsi-videobridge2'
    daemon_reload: true
    state: started
    enabled: true

- name: Jicofo service reload/start
  systemd:
    name: 'jicofo'
    daemon_reload: true
    state: started
    enabled: true
  
# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  copy:
    src: jitsiSSL.conf
    dest: /opt/nginx/conf/server/jitsiSSL.conf

- name: Nginx service restart with full configuration
  systemd:
    name: 'nginx'
    state: restarted
