---
- name: "[PostgreSQL] - PostgreSQL packages are installed"
  package:
    name: "{{ pg_deps }}"
    state: "present"
  vars:
    pg_deps:
      - "postgresql"
      - "php{{ php_ver }}-pgsql"
      - "python{{ '3' if ansible_python.version.major == 3 else '' }}-psycopg2"

- name: "[PostgreSQL] - generate nextcloud role password."
  set_fact: nextcloud_db_pwd="{{ lookup( 'password', 'nextcloud_instances/'+ nextcloud_instance_name +'/pgsql_nc.pwd' ) }}"
  when: nextcloud_db_pwd is not defined

- name: "[PostgreSQL] - nextcloud role is created."
  postgresql_user:
    name: "{{ nextcloud_db_admin }}"
    password: "{{ nextcloud_db_pwd }}"
    encrypted: yes
    state: present
    role_attr_flags: CREATEDB
  become_user: postgres
  become: yes

- name: "[PostgreSQL] - nextcloud database is created."
  postgresql_db:
    name: "{{ nextcloud_db_name }}"
    state: present
    owner: "{{ nextcloud_db_admin }}"
  become_user: postgres
  become: yes
