---
- name: "[APACHE] -  Required and recommended packages are installed."
  package: "name={{ apache2_deps + php_pkg_spe }} state=present"
  vars:
    apache2_deps:
      - apache2
      - smbclient
      - "libapache2-mod-php{{ php_ver }}"
      - "php{{ php_ver }}-ldap"
      - "php{{ php_ver }}-imap"
      - "php{{ php_ver }}-gd"
      - "php{{ php_ver }}-json"
      - "php{{ php_ver }}-curl"
      - "php{{ php_ver }}-intl"
  # notify: start apache2

- name: "[APACHE] - the server is running"
  service:
    name: apache2
    state: started

- name: "[APACHE] -  APCu is installed."
  package: "name={{ php_pkg_apcu }} state=present"
  when: ansible_distribution_release not in [ "trusty" ]

- block:
  # load APCu from backports as the default version for trusty is obsolete.
  - name: "[APACHE] -  Configure trusty backports."
    apt_repository:
      repo: "deb http://fr.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse"
      state: present
      update_cache: yes
    ignore_errors: yes # fix for travis ci
  - name: "[APACHE] -  Install APCu from backports."
    apt: "name={{ php_pkg_apcu }} state=present default_release=trusty-backports"
  when: ansible_distribution_release == "trusty"

- name: "[APACHE] -  enable APC for php CLI"
  lineinfile:
    dest: "{{ php_dir }}/cli/php.ini"
    line: "apc.enable_cli = 1"
    insertbefore: "^; End:$"
    state: present
    # validate: "/usr/sbin/{{ php_bin }} -t #%s"

- name: "[APACHE] -  enable PHP OPcache for php.ini"
  lineinfile:
    dest: "{{ php_dir }}/apache2/php.ini"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - { regexp: 'opcache.enable=0', line: 'opcache.enable=1' }
    - { regexp: 'opcache.enable_cli', line: 'opcache.enable_cli=1' }
    - { regexp: 'opcache.interned_strings_buffer', line: 'opcache.interned_strings_buffer=8' }
    - { regexp: 'opcache.max_accelerated_files', line: 'opcache.max_accelerated_files=10000' }
    - { regexp: 'opcache.memory_consumption', line: 'opcache.memory_consumption=128' }
    - { regexp: 'opcache.save_comments', line: 'opcache.save_comments=1' }
    - { regexp: 'opcache.revalidate_freq', line: 'opcache.revalidate_freq=1' }
    # validate: "/usr/sbin/{{ php_bin }} -t #%s"
  notify: reload apache2

- name: "[APACHE] -  Required Apache2 modules are enabled"
  apache2_module: state=present name={{ item }}
  with_items:
    - rewrite
    - headers
    - env
    - dir
    - mime
  notify: restart apache2

- name: "[APACHE] -  Ssl Apache2 module is enabled"
  apache2_module: state=present name={{ item }}
  with_items:
    - ssl
  when: (nextcloud_install_tls | bool)
  notify: restart apache2

- name: "[APACHE] -  generate Nextcloud configuration for apache"
  template:
    dest: /etc/apache2/sites-available/nc_{{ nextcloud_instance_name }}.conf
    src: "{{ nextcloud_websrv_template }}"
  notify: reload apache2

- name: "[APACHE] -  Enable Nextcloud site in apache conf"
  file:
    path: /etc/apache2/sites-enabled/nc_{{ nextcloud_instance_name }}.conf
    src: /etc/apache2/sites-available/nc_{{ nextcloud_instance_name }}.conf
    state: link
  notify: reload apache2
