---
# tasks file for nextcloud
- include_tasks: ./setup_env.yml
  tags: always
  # load os specific variables

- block:
  - name: Verify permission for installed TLS certificates
    include_tasks: ./tls_installed.yml
    when: nextcloud_tls_cert_method == "installed"

  - name: Install given signed certificates
    include_tasks: ./tls_signed.yml
    when: nextcloud_tls_cert_method == "signed"

  - name: configure self signed TLS certificates
    include_tasks: ./tls_selfsigned.yml
    when: nextcloud_tls_cert_method == "self-signed"
  when: nextcloud_install_tls

- block:
  - name: Configure Nginx web server.
    include_tasks: ./http_nginx.yml
    when: nextcloud_websrv in ["nginx"]

  - name: Configure Apache web server
    include_tasks: ./http_apache.yml
    when: nextcloud_websrv in ["apache", "apache2"]
  when: nextcloud_install_websrv

- name: Configure Redis server
  include_tasks: ./redis_server.yml
  when: (nextcloud_install_redis_server | bool)

- block:
  - name: Configure mysql/mariadb database
    include_tasks: ./db_mysql.yml
    when: nextcloud_db_backend in ["mysql", "mariadb"]

  - name: Configure PostgreSQL database
    include_tasks: ./db_postgresql.yml
    when: nextcloud_db_backend in ["pgsql"]
  when: nextcloud_install_db

- name: Check Nextcloud installed
  stat: "path={{ nextcloud_webroot }}/index.php"
  register: nc_nextcloud_installed

- name: Downloading Nextcloud
  include_tasks: ./nc_download.yml
  when: not nc_nextcloud_installed.stat.exists

- name: Check Nextcloud configuration exists.
  stat: path="{{ nextcloud_webroot }}/config/config.php"
  register: nc_nextcloud_conf

- name: Check Nextcloud is configured
  command: grep -q "{{ nextcloud_trusted_domain| first }}" {{ nextcloud_webroot }}/config/config.php
  failed_when: False
  changed_when: False
  register: nc_nextcloud_configured
  when: nc_nextcloud_conf.stat.exists

- name: Nextcloud installation
  include_tasks: ./nc_installation.yml
  when: |
    (not nc_nextcloud_conf.stat.exists) or
    (nc_nextcloud_configured.rc is defined and nc_nextcloud_configured.rc != 0)
