---

# put a logo in public access to enable BIMI when sending mails with the domain

- name: directory for files under /data
  file:
    path: /data/static-files
    state: 'directory'
    owner: 'nobody'
    group: 'nogroup'

- name: logo SVG image
  copy:
    src: logo.svg
    dest: /data/static-files/logo.svg

- name: generate static certificate
  shell: /usr/bin/certbot certonly -d static.meallier.fr -m eric@meallier.fr --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html  --keep-until-expiring --non-interactive
  when: not redmine_unsecured

# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  template:
    src: static.conf
    dest: /opt/nginx/conf/server/static.conf

- name: Nginx service restart with full configuration
  systemd:
    name: 'nginx'
    state: restarted
