---
# put a logo in public access to enable BIMI when sending mails with the domain


- name: Update DNS
  include_role:
    name : update_infomaniak_dns
  vars:
    targetExtension : '{{static.domain.suffix}}'
    targetIP: '{{ansible_default_ipv4.address}}'
  when: not redmine_unsecured

- name: directory for files under /data
  file:
    path: /data/static-files
    state: 'directory'
    owner: 'nobody'
    group: 'nogroup'

- name: logo SVG image
  copy:
    src: logo.svg
    dest: /data/static-files/logo.svg

- name: generate static certificate
  shell: /usr/bin/certbot certonly -d {{ static.domain.suffix }}.{{ server.domain.sub}}{{server.domain.main }} -m {{ server.domain.contact }} --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html  --keep-until-expiring --non-interactive
  when: not redmine_unsecured

# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  template:
    src: static.conf
    dest: /opt/nginx/conf/server/static.conf

- name: Nginx service restart with full configuration
  systemd:
    name: 'nginx'
    state: restarted
