---

- name: generate certificate
  shell: /usr/bin/certbot certonly -d pico.meallier.fr -m eric@meallier.fr --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html  --keep-until-expiring --non-interactive  
      
# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  copy:
    src: picoSSL.conf
    dest: /opt/nginx/conf/server/picoSSL.conf

- name: Nginx service restart with full configuration
  systemd:
    name: 'nginx'
    state: restarted
