---

- name: Copy unsecured nginx configuration file
  copy:
    src: picoUnsecured.conf
    dest: /opt/nginx/conf/server/picoUnsecured.conf

- name: Nginx service reload/start
  systemd:
    name: 'nginx'
    daemon_reload: true
    state: restarted
    enabled: true
