---

- name: Install API calls pre requisites
  ansible.builtin.apt:
    name:
      - jq
      - curl
    state: present

- name: Get record ID
  ansible.builtin.shell: "set -o pipefail && curl -s {{ infomaniak.api_url }}2/zones/{{ server.domain.sub }}{{ server.domain.main }}/records --header 'Authorization: Bearer {{ infomaniak.token }}' | jq -r --arg record {{ update_infomaniak_dns_target_extension }} '.data | map(select(.source == $record)) | .[0].id'"
  register: record_id

- name: Update record
  ansible.builtin.shell: "set -o pipefail && curl -s -X PUT -d target={{ update_infomaniak_dns_target_ip }} -d ttl={{ extension.ttl }} '{{ infomaniak.api_url }}2/zones/{{ server.domain.sub }}{{ server.domain.main }}/records/{{ record_id.stdout }}' --header 'Authorization: Bearer {{ infomaniak.token }}'"
  when: record_id.stderr | length == 0
