---
- name: Ensure group "moodle" exists
  group:
    name: moodle
    state: present

- name: Add the user 'moodle'
  user:
    name: moodle
    group: moodle

- name: install moodle pre requisites
  apt: 
    name:
    - php7.3-intl
    - php7.3-soap
    - php7.3-xmlrpc
    - php7.3-pgsql
    state: present
    
- name: Download moodle files
  get_url:
    url: https://download.moodle.org/stable{{ moodle.version }}/moodle-latest-{{ moodle.version }}.tgz
    dest: '/tmp/moodle-{{ moodle.version }}.tgz'

- name: Extract moodle files into /opt
  unarchive:
    src: '/tmp/moodle-{{ moodle.version }}.tgz'
    dest: /opt
    remote_src: 'yes'
    owner: moodle
    group: moodle

- name: Configuration folder creation
  file:
    path: '/data/moodle'
    state: 'directory'
    owner: nobody
    group: nogroup

- name: Copy configuration file
  template:
    src: config-dist.php
    dest: /opt/moodle/config.php
    owner: moodle
    group: moodle
    mode: '0644'

- name: 'Insecure configuration (for Vagrant)'
  include: unsecure.yml
  when: redmine_unsecured
    
- name: 'Secure configuration (for Internet)'
  include: secure.yml
  when: not redmine_unsecured
