---
- name: adding apt repo
  shell: echo 'deb https://download.jitsi.org stable/' >> /etc/apt/sources.list.d/jitsi-stable.list

- name: adding apt repo key
  shell: wget -qO -  https://download.jitsi.org/jitsi-key.gpg.key | apt-key add -

# Warning, you will be asked to enter domain name jitsi.meallier.fr manually
- name: adding jitsi meet
  apt: 
    name:
    - jitsi-meet
    state: present

- name: 'Insecure configuration (for Vagrant)'
  include: unsecure.yml
  when: redmine_unsecured
    
- name: 'Secure configuration (for Internet)'
  include: secure.yml
  when: not redmine_unsecured

- name: logrotate configuration
  copy:
    src: logrotate
    dest: /etc/logrotate.d/gogs  