---

- name: install ethercalc pre requisites
  apt: 
    name:
    - redis
    state: present

- name: Ensure group "ethercalc" exists
  group:
    name: ethercalc
    state: present

- name: Add the user 'ethercalc'
  user:
    name: ethercalc
    group: ethercalc

- name: Download ethercalc files
  npm:
    name: ethercalc
    global: yes
    state: present

- name: Install ethercalc service script
  copy:
    src: ethercalc.service
    dest: /etc/systemd/system/ethercalc.service
    owner: root
    group: root
    mode: '0644'

- name: ethercalc service reload/start
  systemd:
    name: 'ethercalc'
    daemon_reload: true
    state: started
    enabled: true
 
- name: generate ethercalc certificate
  shell: /usr/bin/certbot certonly -d {{ ethercalc.domain.suffix }}.{{ server.domain.sub}}{{server.domain.main }} -m {{ server.domain.contact }} --agree-tos --webroot --no-eff-email --webroot-path /opt/nginx/html  --keep-until-expiring --non-interactive
  when: not redmine_unsecured
      
# finish installation with ssl termination
- name: Copy full nginx ssl configuration file
  template:
    src: ethercalc.conf
    dest: /opt/nginx/conf/server/ethercalc.conf

- name: Nginx service restart with full configuration
  systemd:
    name: 'nginx'
    state: restarted
