---

- name: install package
  apt: 
    name:
    - fail2ban
    state: present

- name: active nginx supervision
  copy:
    src: customNginx.conf
    dest: /etc/fail2ban/jail.d/customNginx.conf
    mode: '0640'

- name: Service restart
  systemd:
    name: 'fail2ban'
    state: restarted